services:
    wintstar.hideprofilelink.listener:
        class: wintstar\hideprofilelink\event\listener
        arguments:
            - '@auth'
            - '@user'
            - '@language'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
